PermitRootLogin no
PasswordAuthentication no
PrintMotd no
HostKey /etc/ssh/keys/ssh_host_ed25519_key
HostKey /etc/ssh/keys/ssh_host_rsa_key

Match User nethack
    AuthenticationMethods none
    PasswordAuthentication yes
    PermitEmptyPasswords yes
    ForceCommand /usr/local/bin/dgamelaunch
    PermitTTY yes
    X11Forwarding no
    AllowTcpForwarding no
    AllowAgentForwarding no
